[package]
name = "sologger_log_transport"
version = "0.4.0"
edition = "2021"
rust-version.workspace = true
authors = ["Will Kennedy"]
description = "Provides support for both LogStash and OpenTelemetry exports for logs."
license = "Apache-2.0"
repository = "https://github.com/brytelands/sologger"
readme = "README.md"
keywords = ["solana", "logstash", "opentelemetry", "logging"]
categories = ["development-tools::debugging"]
exclude=["/tests", "/examples", "/benches", "/docs", "/target", "/.github", "/.gitignore", "/.gitattributes", "/.gitmodules", "/.travis.yml", "/.cargo-ok", "/.git", "/.idea"]

[lib]
doctest = false

[dependencies]
log = "0.4"
opentelemetry-otlp = {version = "0.32.0", features = ["grpc-tonic", "logs", "metrics", "trace"], optional = true}
opentelemetry-appender-log = {version = "0.32.0", default-features = false, optional = true}
opentelemetry = {version = "0.32.0", features = ["logs", "metrics", "trace"]}
opentelemetry_sdk = {version = "0.32.0", features = ["metrics", "logs", "trace"], optional = true}
opentelemetry-stdout = {version = "0.32.0", features = ["logs", "metrics", "trace"], optional = true}
qoollo-logstash-rs = { version = "0.2.0", optional = true }
qoollo-log4rs-logstash = { version = "0.2.0", optional = true }
log4rs = { version = "1.4.0", features = ["json_format", "serde_json", "config_parsing"] }
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
sologger_log_context = { version = "0.3.0", optional = true }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"], optional = true }

[dev-dependencies]
tokio = { version = "1.49", features = ["macros"] }
opentelemetry_sdk = { version = "0.32.0", features = ["metrics", "logs", "trace", "testing"] }

[features]
logstash = ["qoollo-logstash-rs", "qoollo-log4rs-logstash"]
otel = ["opentelemetry-otlp", "opentelemetry-appender-log", "opentelemetry_sdk", "opentelemetry-stdout", "sologger_log_context"]
webhook = ["reqwest", "sologger_log_context"]
