refresh_rate: 30 seconds
appenders:
  logstash:
    kind: logstash
    hostname: logstash
    port: 50000
    buffer_size: 10
    log_queue_len: 1000
    buffer_lifetime: 1s
    extra_fields:
      node_id: "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on"
      node_name: "solana-devnet-logs"

# This is where you want to set your log level for your sologger instance. This will set the log level
# for the sologger application itself. This is useful for debugging sologger.
root:
  level: error
  appenders:
    - logstash

# This is where you want to set your log level for your on-chain application.
# There are only two levels to set here: info and error. To listen to all logs emitted from your
# Solana program, set the level to info. If you only want to listen to errors, set the level to error.
loggers:
  sologger::log_processor:
    level: info
    appenders:
      - logstash
    additive: false