[package]
name = "sologger_log_context"
version = "0.1.0"
edition = "2021"
authors = ["Will Kennedy"]
description = "Provides functionality to turn raw logs output by Solana RPCs into structured logs for specified program IDs"
license = "Apache-2.0"
repository = "https://github.com/brytelands/sologger"
readme = "README.md"
keywords = ["solana", "logging", "json", "parsing"]
categories = ["Development tools::Logging"]
exclude=["/tests", "/examples", "/benches", "/docs", "/target", "/.github", "/.gitignore", "/.gitattributes", "/.gitmodules", "/.travis.yml", "/.cargo-ok", "/.git", "/.idea"]

[lib]
doctest = false

[dependencies]
log = "0.4.19"
regex = { version = "1.9.5" }
serde = { version = "1.0.188", features = ["serde_derive", "derive"]}
serde_json = {version = "1.0.107"}
serde_derive = "1.0.188"
bs58 = "0.5.0"
lazy_static = "1.4.0"