refresh_rate: 30 seconds
appenders:
  logstash:
    kind: logstash
    hostname: localhost
    port: 50000
    buffer_size: 100
    log_queue_len: 1000
    buffer_lifetime: 1s
    extra_fields:
      node_id: "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on"
      node_name: "solana-devnet-logs"
root:
  level: INFO
  appenders:
    - logstash